[workspace]
resolver = "3"

members = [
	"bspsuite-buildtasks",
	"bspsuite-core",
	"bspsuite-compiler",
	"bspsuite-ext-goldsrc"
]

[workspace.package]
version = "0.1.0"
authors = ["NoodleCollie"]
documentation = "https://example.com/bar"
edition = "2024"
